# docker-compose.yml
version: '3.8'

services:
  go_project:
    build: ./go_project
    container_name: go_project
    tty: true
    environment:
      - CUSTOM_SEARCH_API_KAY=${CUSTOM_SEARCH_API_KAY}
      - SEARCH_ENGINE_ID=${SEARCH_ENGINE_ID}
      - APP_SCRIPT_ID=${APP_SCRIPT_ID}
    env_file:
      - .env
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"

  python_project:
    build: ./python_project
    container_name: python_project
    tty: true
    depends_on:
      - go_project
